name: Build and Release sbsh

on:
  push:
    branches:
      - main  # 或你默认的分支
  workflow_dispatch: {}  # 允许手动触发

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 准备目录
      - name: Prepare dist directory
        run: |
          mkdir -p dist

      # 3️⃣ 构建 sbsh for each architecture
      - name: Build sbsh for multiple architectures
        run: |
          ARCHS=("amd64" "arm64" "s390x")
          for arch in "${ARCHS[@]}"; do
            cp singbox-auto.sh "dist/sbsh"
            chmod +x "dist/sbsh"
            echo "$arch build done"
          done
          ls -l dist

      # 4️⃣ 创建 Release 并上传每个架构
      - name: Upload sbsh for each architecture
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            dist/sbsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ARCHS=("amd64" "arm64" "s390x")
          for arch in "${ARCHS[@]}"; do
            echo "Creating release for $arch"
            gh release create "sbsh-${arch}-$(date +'%Y%m%d%H%M%S')" dist/sbsh \
              --title "sbsh $arch" --notes "Automatic release for $arch binary" || true
          done